{
 "title": "PI1 Simulated",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Motion panel",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r._measurement == \"Motion sensor\")\r\n  |> filter(fn: (r) => r.simulated == \"True\")\r\n  |> filter(fn: (r) => r.pi == \"PI1\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> fill(column: \"_value\", usePrevious: true)"
    }
   ]
  },
  {
   "title": "Ultrasonic Sensor panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r._measurement == \"Ultrasonic sensor\")\r\n  |> filter(fn: (r) => r.simulated == \"True\")\r\n  |> filter(fn: (r) => r.pi == \"PI1\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> fill(column: \"_value\", usePrevious: true)"
    }
   ]
  },
  {
   "title": "Membrane Switch panel",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r._measurement == \"Membrane switch\")\r\n  |> filter(fn: (r) => r.simulated == \"True\")\r\n  |> filter(fn: (r) => r.pi == \"PI1\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"device\", \"pi\"])\r\n  |> fill(column: \"_value\", usePrevious: true)"
    }
   ]
  },
  {
   "title": "Button panel",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r._measurement == \"Button\")\r\n  |> filter(fn: (r) => r.simulated == \"True\")\r\n  |> filter(fn: (r) => r.pi == \"PI1\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> fill(column: \"_value\", usePrevious: true)"
    }
   ]
  },
  {
   "title": "Buzzer panel",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r._measurement == \"Buzzer\")\r\n  |> filter(fn: (r) => r.simulated == \"True\")\r\n  |> filter(fn: (r) => r.pi == \"PI1\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n"
    }
   ]
  },
  {
   "title": "LED",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r._measurement == \"LED\")\r\n  |> filter(fn: (r) => r.simulated == \"True\")\r\n  |> filter(fn: (r) => r.pi == \"PI1\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n"
    }
   ]
  }
 ]
}