{
 "title": "Data",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "sim", "label": "IsSimulated", "query": "True, False" }
  ]
 },
 "panels": [
  {
   "title": "Motion panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Motion sensor\")\r\n  |> filter(fn: (r) => r.simulated == \"${sim}\")\r\n  |> map(fn: (r) => ({ r with _value: if r._value == \"Motion detected\" then 1 else 0 }))\r\n  |> keep(columns: [\"_time\", \"_value\", \"device\", \"pi\"])\r\n  |> group(columns: [\"device\",\"pi\"])\r\n  |> fill(column: \"_value\", usePrevious: true)"
    }
   ]
  },
  {
   "title": "Ultrasonic Sensor panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Ultrasonic sensor\")\r\n  |> filter(fn: (r) => r.simulated == \"${sim}\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"device\", \"pi\"])\r\n  |> group(columns: [\"device\",\"pi\"])\r\n  |> fill(column: \"_value\", usePrevious: true)"
    }
   ]
  },
  {
   "title": "Membrane Switch panel",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Membrane switch\")\r\n  |> filter(fn: (r) => r.simulated == \"${sim}\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"device\", \"pi\"])\r\n  |> group(columns: [\"device\",\"pi\"])\r\n  |> fill(column: \"_value\", usePrevious: true)"
    }
   ]
  },
  {
   "title": "Button panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Button\")\r\n  |> filter(fn: (r) => r.simulated == \"${sim}\")\r\n  |> map(fn: (r) => ({ r with _value: if r._value == \"Pressed\" then 1 else 0 }))\r\n  |> keep(columns: [\"_time\", \"_value\", \"device\", \"pi\"])\r\n  |> group(columns: [\"device\",\"pi\"])\r\n  |> fill(column: \"_value\", usePrevious: true)"
    }
   ]
  },
  {
   "title": "Buzzer panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Buzzer\")\r\n  |> filter(fn: (r) => r.simulated == \"${sim}\")\r\n  |> map(fn: (r) => ({ r with _value: if r._value == \"STARTED\" then 1 else 0 }))\r\n  |> group(columns: [\"device\"])"
    }
   ]
  },
  {
   "title": "LED",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"LED\")\r\n  |> filter(fn: (r) => r.simulated == \"${sim}\")\r\n  |> map(fn: (r) => ({ r with _value: if r._value == \"TURNED ON\" then 1 else 0 }))\r\n  |> group(columns: [\"device\",\"pi\"])"
    }
   ]
  }
 ]
}