{
 "title": "PI3 Simulated",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "sim", "label": "IsSimulated", "query": "True, False" }
  ]
 },
 "panels": [
  {
   "title": "Master Bedroom DHT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r._measurement == \"DHT\")\r\n  |> filter(fn: (r) => r.simulated == \"True\")\r\n  |> filter(fn: (r) => r.pi == \"PI3\")\r\n  |> filter(fn: (r) => r.device == \"DHT2\")\r\n  |> filter(fn: (r) => r._field == \"temperature\" or r._field == \"humidity\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n"
    }
   ]
  },
  {
   "title": "Bedroom DHT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r._measurement == \"DHT\")\r\n  |> filter(fn: (r) => r.simulated == \"True\")\r\n  |> filter(fn: (r) => r.pi == \"PI3\")\r\n  |> filter(fn: (r) => r.device == \"DHT1\")\r\n  |> filter(fn: (r) => r._field == \"temperature\" or r._field == \"humidity\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n"
    }
   ]
  },
  {
   "title": "Living Room Motion Sensor",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r._measurement == \"Motion sensor\")\r\n  |> filter(fn: (r) => r.simulated == \"True\")\r\n  |> filter(fn: (r) => r.pi == \"PI3\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> fill(column: \"_value\", usePrevious: true)"
    }
   ]
  },
  {
   "title": "Bedroom RGB",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r._measurement == \"RGB LED\")\r\n  |> filter(fn: (r) => r.simulated == \"True\")\r\n  |> filter(fn: (r) => r.pi == \"PI3\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n"
    }
   ]
  },
  {
   "title": "Living room Display",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r._measurement == \"LCD\")\r\n  |> filter(fn: (r) => r.simulated == \"True\")\r\n  |> filter(fn: (r) => r.pi == \"PI3\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n"
    }
   ]
  },
  {
   "title": "Bedroom Infrared",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r._measurement == \"IR Receiver\")\r\n  |> filter(fn: (r) => r.simulated == \"True\")\r\n  |> filter(fn: (r) => r.pi == \"PI3\")\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n"
    }
   ]
  }
 ]
}