{
 "title": "PI2 Simulated",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "sim", "label": "IsSimulated", "query": "True, False" }
  ]
 },
 "panels": [
  {
   "title": "Gyroscope",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r._measurement == \"Gyroscope\")\r\n  |> filter(fn: (r) => r.simulated == \"True\")\r\n  |> filter(fn: (r) => r.pi == \"PI2\")\r\n  |> filter(fn: (r) => r._field == \"accel_x\" or r._field == \"accel_y\" or r._field == \"accel_z\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n"
    }
   ]
  },
  {
   "title": "Motion panel",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r._measurement == \"Motion sensor\")\r\n  |> filter(fn: (r) => r.simulated == \"True\")\r\n  |> filter(fn: (r) => r.pi == \"PI2\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> fill(column: \"_value\", usePrevious: true)"
    }
   ]
  },
  {
   "title": "Kitchen DHT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r._measurement == \"DHT\")\r\n  |> filter(fn: (r) => r.simulated == \"True\")\r\n  |> filter(fn: (r) => r.pi == \"PI2\")\r\n  |> filter(fn: (r) => r._field == \"temperature\" or r._field == \"humidity\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n"
    }
   ]
  },
  {
   "title": "Door sensor (Button)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r._measurement == \"Button\")\r\n  |> filter(fn: (r) => r.pi == \"PI2\")\r\n  |> filter(fn: (r) => r.device == \"DS2\")\r\n  |> filter(fn: (r) => r.simulated == \"True\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> fill(column: \"_value\", usePrevious: true)"
    }
   ]
  },
  {
   "title": "Kitchen 4 Digit 7 Segment Display Timer",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r._measurement == \"4 Digit 7 Segment Display\")\r\n  |> filter(fn: (r) => r.simulated == \"True\")\r\n  |> filter(fn: (r) => r.pi == \"PI2\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> fill(column: \"_value\", usePrevious: true)"
    }
   ]
  },
  {
   "title": "Ultrasonic Sensor panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r._measurement == \"Ultrasonic sensor\")\r\n  |> filter(fn: (r) => r.simulated == \"True\")\r\n  |> filter(fn: (r) => r.pi == \"PI2\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> fill(column: \"_value\", usePrevious: true)"
    }
   ]
  },
  {
   "title": "Kitchen Button",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r._measurement == \"Button\")\r\n  |> filter(fn: (r) => r.pi == \"PI2\")\r\n  |> filter(fn: (r) => r.device == \"BTN\")\r\n  |> filter(fn: (r) => r.simulated == \"True\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> fill(column: \"_value\", usePrevious: true)"
    }
   ]
  }
 ]
}